name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Use NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm --prefix ./v3 install

      - name: Build project
        run: npm --prefix ./v3 run deploy
        
#      - name: Install and Build
#        run: |
#          mkdir -p dist
#          cp -r v3/out/* dist
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          BRANCH: v3
          FOLDER: v3/out
